#!/usr/bin/env python3
"""Read-only adapter for the career-ops staged-applications brief."""
from __future__ import annotations

import subprocess
from pathlib import Path

CAREER_OPS_DIR = Path.home() / "proyectos" / "career-ops"


def collect_career_ops_brief(timeout: int = 30) -> dict:
    """Return brief.mjs stdout verbatim without exposing stderr or mutating stage."""
    try:
        completed = subprocess.run(
            ["node", "brief.mjs", "--quiet"],
            cwd=CAREER_OPS_DIR,
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        return {"status": "unavailable", "reason": type(exc).__name__}
    if completed.returncode != 0:
        return {"status": "unavailable", "reason": "nonzero_exit"}
    # Preserve every character generated by career-ops except the terminal newline
    # added by console.log. An empty stdout is intentionally silent.
    output = completed.stdout[:-1] if completed.stdout.endswith("\n") else completed.stdout
    if not output:
        return {"status": "empty", "verbatim": ""}
    return {"status": "ok", "verbatim": output}
